'use strict';
Object.defineProperty(exports, '__esModule', { value: true });
exports.CONTENT_TYPE_JSON = exports.HTTP_NO_CONTENT = exports.HTTP_CREATED = exports.HTTP_OK = exports.HTTP_INTERNAL_SERVER_ERROR = exports.HTTP_BAD_REQUEST = exports.HTTP_NOT_FOUND = void 0;
exports.HTTP_NOT_FOUND = 404;
exports.HTTP_BAD_REQUEST = 400;
exports.HTTP_INTERNAL_SERVER_ERROR = 500;
exports.HTTP_OK = 200;
exports.HTTP_CREATED = 201;
exports.HTTP_NO_CONTENT = 204;
exports.CONTENT_TYPE_JSON = { 'Content-Type': 'application/json' };
